### ISSUE TITLE
Implement setting that limits the amount of modules the block completion_progress supports

### ISSUE THREAD

**Issue by frederikmillingpytlick** [praxisdigital/moodle-block_completion_progress#1]
**Add setting: "block_completion_progress/max_modules":**
- The amount of modules allowed in a course for the block to show completion progress.
- If the course has more modules than this, the block will not show completion progress. **By setting this setting to 0, the block will always show completion progress.**

**Comment by frederikmillingpytlick** [comment]
@TubsDK why reopen this? :thinking:

**Comment by Mikkeljeppesen1** [comment]
@frederikmillingpytlick could you make a pull request to the original plugin? :)

**Comment by frederikmillingpytlick** [comment]
Remote PR: https://github.com/jonof/moodle-block_completion_progress/pull/105
